# Linear Algebra Crash Course (with Python) Class 9


## Chap 8 Conti

## Example of linear regression

In [ ]:
### 线性回归模块与伪逆矩阵之间的关系

In [228]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [232]:
## example1 
M = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * m_0 + 2 * m_1 + 3
y = np.dot(M, np.array([1, 2])) + 3
print(M)
print(y)

[[1 1]
 [1 2]
 [2 2]
 [2 3]]
[ 6  8  9 11]


In [230]:
reg = LinearRegression().fit(M, y)
reg.score(M, y)

1.0

In [231]:
reg.coef_

array([1., 2.])

In [7]:
reg.intercept_

3.0000000000000018

In [8]:
reg.predict(np.array([[3, 5]]))

array([16.])

In [23]:
M2= np.append(M,[[1],[1],[1],[1]],axis=1)

In [24]:
np.linalg.pinv(M2).dot(y)

array([1., 2., 3.])

In [233]:
## example 2 
M = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
M1 = np.array([M[:,0]**2,M[:,1]**3]).T
M2 = np.array([M[:,0]**2,M[:,1]**3,[1,1,1,1]]).T

# y = 1 * (m_0)^2 + 2 * (m_1)^3 + 3 + noise
y=  M[:,0]**2 + 2*M[:,1]**3 + 3

In [57]:
M2

array([[ 1,  1,  1],
       [ 1,  8,  1],
       [ 4,  8,  1],
       [ 4, 27,  1]])

In [30]:
y

array([ 6, 20, 23, 61])

In [65]:
5*( np.random.rand(4)-0.5)

array([-2.17764712,  2.49896375, -0.74851921,  1.62703593])

In [234]:
yrand = y + 5*( np.random.rand(4)-0.5)

In [237]:
reg = LinearRegression().fit(M1, y)
reg.score(M1, y)

1.0

In [238]:
reg = LinearRegression().fit(M1, yrand)
reg.score(M1, yrand)

0.9987704742979117

In [239]:
reg.coef_

array([0.52052596, 2.15722953])

In [240]:
reg.intercept_

2.6463959472671554

In [241]:
np.linalg.pinv(M2).dot(yrand)

array([0.52052596, 2.15722953, 2.64639595])

## Chap 9 特征值、特征向量、特征方程式

### 特征方程式
我们***可以定义***一个方阵 $A$ 的 $\lambda$ 特征多项式 $\mathtt{det}(A-\lambda \boldsymbol{I})$，以及特征方程式 $\mathtt{det}(A-\lambda \boldsymbol{I})=0$。
不难检查 $\lambda$ 特征多项式的最高次方为 $n$。


可以考虑如果有$\lambda$ 使得 $\mathtt{det}(A-\lambda \boldsymbol{I})=0$，则 $A-\lambda \boldsymbol{I}$ 不可逆，则 $\exists\;  \mathbf{ v}_{\lambda}\neq0\in \mathbb{R}^n \Rightarrow(A-\lambda \boldsymbol{I})\mathbf{  v}_{\lambda}=0 \Rightarrow A\mathbf{  v}_{\lambda}=\lambda\mathbf{  v}_{\lambda}$。我们称 $\lambda$ 是是一个特征值，以及 $\mathbf{  v}_{\lambda}$是对应的特征向量。

**代数基本定理：任何一个非常数、单变数、复数系数方程式，都至少有一个复数解**

> 高斯一辈子对**代数基本定理** 给出了4 种证明，有复分析、拓扑学、积分、代数等等。同时 **代数基本定理** 是高斯 22 岁的博士论文。

假设 $A$ 是一个实系数方阵，则显然 $\mathtt{det}(A-\lambda \boldsymbol{I})=0$ 是个实系数方程式，因此我们可以引用代数基本定理，*确保解一定存在*。更进一步对整个方程式取共轭时，可得到当 $\lambda$ 是一个特征值因为 $\mathbf{v}_{\lambda}$ 是它的特征向量，它的共轭 $\bar{\lambda}$ 也是一个特征值， $\bar{\mathbf{v}}_{ \lambda}$ 是它的共轭特征向量。


### 对角线化矩阵

如果一个 $n\times n$ 方阵 $\mathbf{A}$，有 $n$ 个相异的特征值 $\{\lambda_i\}$，以及对应的特征向量$\{\mathbf{v}_i\}$。
這些$\{\mathbf{v}_i\}$都是線型獨立的。考慮 $n=2$，结论显然成立。使用数学归纳法以及反證法，考虑$n=j+1$，若 $\mathbf{v}_{j+1}=\sum x_i\mathbf{v}_{i}$。我们有 $\lambda_{j+1}\mathbf{v}_{j+1}=\sum \lambda_{j+1} x_i\mathbf{v}_{i}$。类似的作用$A$在等式兩邊得到 $\lambda_{j+1}\mathbf{v}_{j+1}=\sum \lambda_{i} x_i\mathbf{v}_{i}$。因此 $\sum (\lambda_{i}-\lambda_{j}) x_i\mathbf{v}_{i}=0$, 跟$n=j$ 時，$\{\mathbf{v}_i\}$ 線型獨立的前提矛盾。

因此我们有
$$\mathbf{A}=\mathbf{VDV}^{-1}$$
或
$$\mathbf{AV}=\mathbf{VD}$$
其中$\mathbf{V}$ 的列向量是$\{\mathbf{v}_i\}$，$\mathbf{D}=（\delta_{ij}d_{ij}）$ 是对角线矩阵,$d_{ii}=\lambda_i$。

问题在于特征值$\{\lambda_i\}$，可能不到 $n$ 个。
比如令
$$A=\begin{bmatrix}
0 & 0 & 0 &0\\
1 & 0 & 0 &0 \\
0 & 1&0& 0\\
0 & 0 & 1 &0\\
 \end{bmatrix}$$
我们发现 $A^4=0$,因此 $A$ 的特征值只可能是0，但$A\mathbf{v}=0$,只有一个解 $[0,0,0,1]^T$, 并且我们有 $A^4[1,0,0,0]^T=A^3[0,1,0,0]^T=A^2[0,0,1,0]^T=A[0,0,0,1]^T=0$。就好像甲板上站了四个人，每次往前走一步，都有一个人会跳进水里。
简单操作一下 $A$ 得到 $A+\lambda\mathbf{I}$，我们可以得到特征值为 $\lambda$ 的矩阵，但一样只有一个特征向量。  Jordan Canonical form.
事实上与其说一般的矩阵都可以对角化，不如说我们举的特例这更接近于一般的情况。但能对角化的确有很多好处，所以我们下面讨论特殊可对角化的矩阵。


### 复向量的内积

我们首先扩充一下内积的定义范围，从 $\mathbb{R}^n\times\mathbb{R}^n\rightarrow \mathbb{R}$, 到 $\mathbb{C}^n\times\mathbb{C}^n\rightarrow \mathbb{C}$. 在复向量空间中，定义维度为 $n$ 的两个复向量 $\mathbf{v}$ 和 $\mathbf{w}$ 的内积为：

$\langle \mathbf{v},\mathbf{w} \rangle = \sum_{i=1}^n v_i \overline{w_i}$

其中 $v_i$ 和 $w_i$ 分别表示 $\mathbf{v}$ 和 $\mathbf{w}$ 的第 $i$ 个分量，$\overline{w_i}$ 表示 $w_i$ 的复共轭。

这个内积满足以下性质：

1.  第一个参数的线性性：对于任意复常数 $\alpha$ 和 $\beta$ 以及复向量 $\mathbf{v}$、$\mathbf{u}$ 和 $\mathbf{w}$，有 $\langle \alpha \mathbf{v} + \beta \mathbf{u}, \mathbf{w} \rangle = \alpha \langle \mathbf{v}, \mathbf{w} \rangle + \beta \langle \mathbf{u}, \mathbf{w} \rangle$。
2.  共轭对称性：对于任意复向量 $\mathbf{v}$ 和 $\mathbf{w}$，有 $\langle \mathbf{v}, \mathbf{w} \rangle = \overline{\langle \mathbf{w}, \mathbf{v} \rangle}$。
3.  正定性：对于任意非零复向量 $\mathbf{v}$，有 $\langle \mathbf{v}, \mathbf{v} \rangle > 0$。


需要注意的是，这种定义方式的内积也诱导出了一个复向量的距离，即 $|\mathbf{v}| = \sqrt{\langle \mathbf{v}, \mathbf{v} \rangle}$。

原本我们有$\langle \mathbf{A}^T\mathbf{v},\mathbf{w}\rangle=\langle \mathbf{v},\mathbf{A}\mathbf{w}\rangle,\; \forall \mathbf{v},\mathbf{w}\in \mathbb{R}^n$。我们现在有 $\langle \mathbf{A}^*\mathbf{v},\mathbf{w}\rangle=\langle \mathbf{v},\mathbf{A}\mathbf{w}\rangle,\; \forall \mathbf{v},\mathbf{w}\in \mathbb{C}^n$，其中$\mathbf{A}^*=\bar{\mathbf{A}}^T$，意即 $\mathbf{A}$ 转置后取共轭，或共轭后取转置。因此  $\langle \bar\lambda\mathbf{v},\mathbf{w}\rangle=\langle \mathbf{v},\lambda \mathbf{w}\rangle$


### 对称矩阵的特征值与特征向量

假设 $\mathbf{S}$ 是一个实系数对称矩阵（方阵），显然 $\mathbf{S}^*=\mathbf{S}$。考虑我们有一个复特征值 $\lambda$，以及对应的复特征向量 $\mathbf{v}_{\lambda}\in \mathbb{C}^n$。我们考虑 $\bar{\lambda}\langle \mathbf{v}_{\lambda},\mathbf{v}_{\lambda}\rangle=\langle \mathbf{v}_{\lambda},\lambda\mathbf{v}_{\lambda}\rangle=\langle \mathbf{v}_{\lambda},\mathbf{S}\mathbf{v}_{\lambda}\rangle=\langle \mathbf{S}^*\mathbf{v}_{\lambda},\mathbf{v}_{\lambda}\rangle=\langle \mathbf{S}\mathbf{v}_{\lambda},\mathbf{v}_{\lambda}\rangle=\langle \lambda\mathbf{v}_{\lambda},\mathbf{v}_{\lambda}\rangle=\lambda\langle \mathbf{v}_{\lambda},\mathbf{v}_{\lambda}\rangle$
因此 $\bar{\lambda}=\lambda$，实对称方阵的特征值一定是实数，并且可推知特征向量也都是实向量。

我们也可以不使用复空间内积符号。 考虑 $\mathbf{S}\mathbf{v}_{\lambda}=\lambda \mathbf{v}_{\lambda}$,取转置共轭我们得到 $\bar{\mathbf{v}}_{\lambda}^T \mathbf{S}^*=\bar{\mathbf{v}}_{\lambda}^T\mathbf{S}=\bar{\lambda} \bar{\mathbf{v}}_{\lambda}^T$。
使用矩阵乘法，我们得到 $\bar{\lambda} \bar{\mathbf{v}}_{\lambda}^T \mathbf{v}_{\lambda}=(\bar{\mathbf{v}}_{\lambda}^T\mathbf{S}) \mathbf{v}_{\lambda}=\bar{\mathbf{v}}_{\lambda}^T\mathbf{S} \mathbf{v}_{\lambda}=\bar{\mathbf{v}}_{\lambda}^T(\mathbf{S}\mathbf{v}_{\lambda})=\lambda\bar{\mathbf{v}}_{\lambda}^T\mathbf{v}_{\lambda}$。因此 $\lambda$ 是实数。

得知对于对称矩阵，特征值、特征向量都是实数后，我么可以暂时忘记复空间内积。

考虑对称矩阵 $S$ 两个不同的特征值 $\lambda，\gamma$ 以及其对应的特征向量 $\mathbf{v}_{\lambda},\mathbf{v}_{\gamma}$ 。我们有$\lambda\langle \mathbf{v}_{\lambda},\mathbf{v}_{\gamma}\rangle=\langle \mathbf{S}\mathbf{v}_{\lambda},\mathbf{v}_{\gamma}\rangle=\langle \mathbf{v}_{\lambda},\mathbf{S}\mathbf{v}_{\gamma}\rangle=\gamma\langle \mathbf{v}_{\lambda},\mathbf{v}_{\gamma}\rangle\Rightarrow (\lambda-\gamma)\langle \mathbf{v}_{\lambda},\mathbf{v}_{\gamma}\rangle=0$, 因此可知 $\mathbf{v}_{\lambda} \perp\mathbf{v}_{\gamma}$。


### 对称矩阵的对角线化

对称矩阵的重要性质是，每个特征值对应一个互相垂直的特征子空间，对称矩阵是完全可以对角线化的，不存在一般矩阵的恶劣情况。

我们使用数学归纳法，明显 $n=1$ 成立，假设 $n=j$ 成立，对于 $n=j+1$,我们先从一个特征值 $\lambda$ ，与其对应的特征单位向量 $\mathbf{v}_{\lambda}$ 出发。因为  $\mathbf{A}\mathbf{v}_{\lambda}=\lambda\mathbf{v}_{\lambda}$ 因此
$$\begin{pmatrix}\mathbf{v}_{\lambda}^T \\
    (\mathbf{v}_{\lambda}^\perp)^T  \\
 \end{pmatrix}\mathbf{A}\begin{pmatrix}
       & \\
   \mathbf{v}_{\lambda} &\mathbf{v}_{\lambda}^\perp   \\
	&\end{pmatrix}=\begin{pmatrix}
       \lambda& \mathbf{?}\\
    \mathbf{0} &\mathbf{*}  
\end{pmatrix}$$


我们观察几件事，首先 
$$\begin{pmatrix}
       & \\
    \mathbf{v}_{\lambda} &\mathbf{v}_{\lambda}^\perp  \\ &
\end{pmatrix}$$ 是实数单位正交矩阵。而且整体保持对称性，因此我们有
$$\begin{pmatrix}
      \mathbf{v}_{\lambda}^T \\
    (\mathbf{v}_{\lambda}^\perp)^T  \\
\end{pmatrix}\mathbf{A}\begin{pmatrix}
       & \\
    \mathbf{v}_{\lambda} &\mathbf{v}_{\lambda}^\perp   \\ &
\end{pmatrix}=\begin{pmatrix}
       \lambda& \mathbf{0}\\
    \mathbf{0} &S_j  
\end{pmatrix}$$

其中$S_j$ 是一个 $j\times j$ 的实对称矩阵。对于$\mathbf{S}_j$ 我们有
$$S_j=V_jD_jV^{T}_j$$
所以
$$\begin{pmatrix}
       \lambda& \mathbf{0}\\
    \mathbf{0} &S_j  
\end{pmatrix}=\begin{pmatrix}
       1& \mathbf{0}\\
    \mathbf{0} &V_j 
\end{pmatrix}\begin{pmatrix}
       \lambda& \mathbf{0}\\
    \mathbf{0} &D_j  
\end{pmatrix}\begin{pmatrix}
       1& \mathbf{0}\\
    \mathbf{0} &V_j^T 
\end{pmatrix}$$
因此最终对于任意对称实数矩阵$\mathbf{A}$我们有以下分解。

$$\mathbf{A}=\mathbf{V}\mathbf{D}\mathbf{V}^{T}$$
其中 $\mathbf{D}$ 是一个对角线矩阵，$\mathbf{V}$ 是一个单位正交矩阵 $\mathbf{V}^T=\mathbf{V}^{-1}$。

## Chap 10 奇异值分解

### 格拉姆矩阵与协方差矩阵

实矩阵 $A ： \mathbb{R}^n \to \mathbb{R}^m$ 一般不是个方阵也不对称，如何制造出一个对称的矩阵呢？其实我们在[[点到子空间的距离]]其实已经用过了,对于任意一个实矩阵 $A$ 而言，$A^TA$ 称作 $A$ 的格拉姆矩阵，而$AA^T$ 称之为协方差矩阵，这两者都是实对称矩阵。并且有进一步的性质。

对于一般矩阵A来说，其格拉姆矩阵与协方差矩阵的特征值是非负的。对于可逆方阵来说，其格拉姆矩阵与协方差矩阵的特征值是正的。

$$\langle A^TA\mathbf{v},\mathbf{v}\rangle=\langle A\mathbf{v},A\mathbf{v}\rangle=|A\mathbf{v}|^2\geq0,\;\forall \mathbf{v}$$

根据[[特征值#对称矩阵的对角线化]]我们有以下分解
$$A^TA=V\Sigma^2V^T$$
其中 $V$ 是实单位正交矩阵。$\Sigma^2=(\delta_{ij}\sigma_{ij}^2)$ 是实对角矩阵（方阵）。



### 奇异值分解

对于一般矩阵 $A$
$A^TA$ 的对角化分解，与$A$ 的奇异值分解有密切的关系。延续上一节的内容，

$V$ 的列向量 $\{\mathbf{v}_i\}$ 自然互相垂直，我们首先证明 $\{A\mathbf{v}_i\}$ 也互相垂直。
考虑 $$\langle A\mathbf{v}_i,A\mathbf{v}_j\rangle=\langle \mathbf{v}_i,A^TA\mathbf{v}_j\rangle=\langle \mathbf{v}_i,\sigma^2_{jj}\mathbf{v}_j\rangle=0$$
我们将 $\{A\mathbf{v}_i\}$ 单位化，并且用单位垂直向量补足其在 $\mathbb{R}^m$ 中缺少的部分，成为  $\{\mathbf{u}_i\}$，同时可以获得$\{\sigma_i\}$。我们则有奇异值分解$$A=U\Sigma V^T$$
或

$$A=\sum \sigma_{ii}  \mathbf{u}_i \mathbf{v}_i^T$$
其中 $U,V$ 都是单位正交矩阵，或者 unitary matrix（real） = orthogonal matrix = orthonormal matrix（注意$U,V$维数不同）而 $\Sigma=(\delta_{ij}\sigma_{ij})$ 是实对角矩阵（非方阵）。$\sigma_{11} \geq \sigma_{22} \geq \sigma_{33}\dots \geq 0$ 亦即 $\Sigma \geq 0$。

 假设我们忽略 $\mathbf{u}_i, \mathbf{v}_i$ 可以同时变号,$U,V$ 是唯一的。

依据奇异值分解，我们可以计算 $A^TA=V \Sigma^T U^T U\Sigma V^T=V \Sigma \Sigma V^T$ 。显然 "$\Sigma^T \Sigma \sim \Sigma^2$ "。

### 从奇异值分解看方程式解

Consider $Ker(A)\neq\phi$  :$A\mathbf x=\mathbf b$ Too many solutions
$Im(A)$ is not full. :$A\mathbf x=\mathbf b$ No solutions. can only find best approximation

Example 
 $\hat{I}_{3\times3} ： \mathbb{R}^3 \to \mathbb{R}^5$,
 $\bar{I}_{3\times3} ： \mathbb{R}^5 \to \mathbb{R}^3$, 

$A\mathbf x=\mathbf b\Leftrightarrow U\Sigma V^T \mathbf x=\mathbf b\Leftrightarrow  \Sigma V^T \mathbf x=U^T\mathbf b \Leftrightarrow \Sigma  \mathbf x'=\mathbf b'$
$\hat{\mathbf x}=A_{pinv}\mathbf b$




### 与实对称矩阵分解的区别

作为一个特殊例子，任何  n × n  实对称矩阵，它们的特征值是实数（可能为负数）
As a special case, for every n × n real symmetric matrix, the eigenvalues are real and the eigenvectors can be chosen real and [orthonormal](https://en.wikipedia.org/wiki/Orthonormal). Thus a real symmetric matrix A can be decomposed as $A=Q \Lambda Q^T$ with $|\lambda_1| \geq |\lambda_2| \geq |\lambda_3| \geq …$ notice that $\lambda$ could have negative values. However we have $\lambda_i^2$=$\sigma_i^2$。

### 矩阵压缩

矩阵压缩就相当于排除较小的 $\sigma_{ii}$ 。

### 奇异值分解应用

**推荐系统** 人 - 物 
**脑机界面** 指令 - 讯号 
**时空大数据** 点对点交通流量 - 时间（日）
	Origin - Destination 
	问题: 有些地方一天无法到达，需要几天，所以 OD 最好只包含一日能到达的地方 
**气候、智慧城市** 点温度变化 - 时间（年、日、时） 
**Music Genre Classification** Text Style - Melody 
**Image compressing** - X Y 
**Video Forensics** - X Y  辨识伪造
**Sports Analytics** - Score，Player Data (假设球员球感或低谷期会维持一段时间)
**Social Network Analysis** P2P, n 个人 adjacency matrix 连接矩阵
还有别的应用，比方说用网路 Chatgpt 可以把非结构化资料结构化。股票报告分析

### 奇异值分解弱点

**非线性**，比方说我们创造一种语言，单词只有三个字母： ABC ABS SOS EVD...  ABC 跟 ABS（塑料）虽然只差了一个英文字母，但意义差很多。

神经网路，处理非线性。

神经网路，假设现实世界可以用函数表示（可能是个随机函数），是对函数的非线性拟合。但是根据微积分，局部都是线性（有可能加一些噪音）。

还是 ABC， ABS的例子。现在可能是手写的 ABC，跟 ABS。在很多 ABS 的不同字迹中间，SVD还是有用。