# Linear Algebra Crash Course (with Python) Class 3

# Chap 3: 3d symmetric matrix

## The importance of eigen-decomposition

Eigenvalue and eigenvector decomposition is an important tool for matrix decomposition. It allows representing a matrix as a combination of eigenvectors and eigenvalues. This decomposition provides finite dimensional approximate solutions for systems of differential equations in the form of Fourier series, with extensive applications in classical and quantum physics research. 

- For example, it can be used to find the **eigenstates(eigenfunction) of the Schrödinger equation** for describing quantum systems. 

Additionally, eigenvalue and eigenvector decomposition serves as an effective technique for assessing the inherent structure and significance of high-dimensional data.
- For instance, Google's PageRank(a pun) algorithm constructs **a transition matrix based on the link structure between webpages** and then ranks pages according to the magnitude of the corresponding eigenvalue. 

It is evident that eigenvalue decomposition is an important tool connecting linear algebra, numerical analysis, and data analysis. Its applications are far-reaching, playing a crucial role in scientific computing and data science research.

***Could be a research topic***


## The failure of eigen-decomposition

However, not every $n$ by $n$ square matrix could process a full set eigen-decomposition consisted of $n$ eigenvalues and $n$ eigenvectors. 

Example:

$\mathbf{A}=\begin{bmatrix}
0 & 0 & 0 &0\\
1 & 0 & 0 &0 \\
0 & 1&0& 0\\
0 & 0 & 1 &0\\
\end{bmatrix}$

We can see $\mathbf{A}^4=0$. Therefore the only possible eigenvalue of $\mathbf{A}$ is $0$. However when we solve the equation $\mathbf{A}\mathbf{v}=0$, we only get one solution $[0,0,0,1]^T$, and we have  $A^4[1,0,0,0]^T=A^3[0,1,0,0]^T=A^2[0,0,1,0]^T=A[0,0,0,1]^T=0$. It's like there are four people standing on a deck, and every time they take a step forward, one person jumps into the water.

***exercise:write down $\mathbf{A}$, $\mathbf{A}^2$, $\mathbf{A}^3$***


In other cases, eigenvalues and their eigenvectors decomposition could result in complex variables. Their (physical) meaning could be a bit hard to understand.

## The wonderful symmetric matrix

Symmetric matrices are really a special kind of matrices and appear everywhere in science world. We shall state their usages & good properties, demonstrate how to compute them with python, and leave the proof of following statements to the later chapters.

Nevertheless, we should prove the failure of eigen-decomposition of genereal matrices would not happen again with symmetric matrices and state 

Assume $\mathbf{S}^n \mathbf{u}=0$, and $\mathbf{S}^{n-1} \mathbf{u}\neq0$, where $\mathbf{S}$ is a symmetric matrix, $n\geq2$, and $\mathbf{u}$ is a non-zero vector. Let $\mathbf{v}=\mathbf{S}^{n-2} \mathbf{u}$, then we get $\mathbf{v}\neq0$, $\mathbf{S}\mathbf{v}\neq0$, and $\mathbf{S}^2\mathbf{v}=0$. Consider $0=\langle \mathbf{v},\mathbf{S}^2\mathbf{v}\rangle=\langle \mathbf{S}^{\top}\mathbf{v},\mathbf{S}\mathbf{v}\rangle=\langle \mathbf{S}\mathbf{v},\mathbf{S}\mathbf{v}\rangle = |\mathbf{S}\mathbf{v}|^2$, then we have $\mathbf{S}\mathbf{v}=0$ which is a contradiciton.

With the same technique, we could prove many other things (like the following statements).

## Eigen-decomposition of symmetric matrix (Spectral theory)

*Statement: Every symmetric matrix could process a full set eigen-decomposition consisted of $n$ eigenvalues and $n$ eigenvectors.* 

*Statement:The eigenvectors of a symmetric matix are orthogonal to each other.*

Therefore the transition matrix is orthonormal. We could write down their eigen-decomposition in the form of

$$\mathbf{S}\mathbf{U} = \mathbf{U}\mathbf{D}$$

$$\mathbf{S} = \mathbf{U}\mathbf{D}\mathbf{U}^{-1} =\mathbf{U}\mathbf{D}\mathbf{U}^{\top}$$

With this understanding, we could state one usage of symmetric matrix.

Consider $f(x,y)= 2x^2-3y^2$ which corresponds to symmetric matrix $\begin{bmatrix}2 & 0 \\0 & -3  \end{bmatrix}$ and quadratic form $\begin{bmatrix}x &y \end{bmatrix}\begin{bmatrix}2 & 0 \\0 & -3  \end{bmatrix}\begin{bmatrix}x \\y \end{bmatrix}$. Now we consider the maximum and minumum of $f(x,y)$ with a constraint $x^2+y^2=1$

It is not hard to see the maximum and minumum happens at $(1,0),(0,1)$. Obviously, the similiar statement could be applied to other diagonal matrix.

Consider $x^2+2xy+2y^2$ which corresponds to symmetric matrix $\mathbf{S}=\begin{bmatrix}1 & 1 \\1 & 2  \end{bmatrix}$ and quadratic form $\begin{bmatrix}x &y \end{bmatrix}\begin{bmatrix}1 & 1 \\1 & 2  \end{bmatrix}\begin{bmatrix}x \\y \end{bmatrix}$. Now we consider the maximum and minumum of $f(x,y)$ with a constraint $x^2+y^2=1$

By the eigen-decomposition $\mathbf{S} = \mathbf{U}\mathbf{D}\mathbf{U}^{\top}$, we see if $|\mathbf{x}|=1$, then $|\mathbf{U}\mathbf{x}|=1$. Therefore every quadratic form is corresponding to a diagonal matrix and their extreme value problem around unit circle could be solved accordingly.


In [2]:
import numpy as np

In [34]:
A = np.array([[1,1],[1,2]])
evalues1, evectors1 = np.linalg.eig(A)
print('The eigenvectors are:')
print(evectors1)
print('The eigenvalues are:')
print(evalues1)

print(np.dot(evectors1,evectors1.T))
print(evectors1.T[0])
print(evalues1[0]*evectors1.T[0])
print(np.dot(A,evectors1.T[0]))

The eigenvectors are:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
The eigenvalues are:
[0.38196601 2.61803399]
[[1. 0.]
 [0. 1.]]
[-0.85065081  0.52573111]
[-0.3249197   0.20081142]
[-0.3249197   0.20081142]


In [5]:
A = np.array([[0,1],[0,0]])
evalues1, evectors1 = np.linalg.eig(A)
print('The eigenvectors are:')
print(evectors1)
print('The Inner product of eigenvectors are:')
print(np.dot(evectors1.T,evectors1))
print('The eigenvalues are:')
print(evalues1)
print('The First Eigenvector is:')
print(evectors1.T[0])
print('The First Eigenvector times first eigenvalue is:')
print(evalues1[0]*evectors1.T[0])
print(np.dot(A,evectors1.T[0]))

The eigenvectors are:
[[ 1.00000000e+000 -1.00000000e+000]
 [ 0.00000000e+000  2.00416836e-292]]
The eigenvectors are:
[[ 1. -1.]
 [-1.  1.]]
The eigenvalues are:
[0. 0.]
The First Eigenvector are:
[1. 0.]
[0. 0.]
[0. 0.]


In [45]:
A = np.random.randint(1, 10, size=(4, 4))

print(A)
evalues1, evectors1 = np.linalg.eig(A)
print(np.dot(A,A.T))
evalues2, evectors2 = np.linalg.eig(np.dot(A,A.T))

print('The eigenvalues are:')
print(evalues1)
print('The eigenvectors are:')
print(evectors1)
print('The Inner product of eigenvectors are:')
print(np.dot(evectors1.T,evectors1))
print('The First Eigenvector is:')
print(evectors1.T[0])
print('The First Eigenvector times first eigenvalue is:')
print(evalues1[0]*evectors1.T[0])
print(np.dot(A,evectors1.T[0]))
print('=================================')
print('Symmetric matrix')

print('The eigenvalues are:')
print(evalues2)
print('The eigenvectors are:')
print(evectors2)
print('The Inner product of eigenvectors are:')
print(np.dot(evectors2.T,evectors2))
print('The First Eigenvector is:')
print(evectors2.T[0])
print('The First Eigenvector times first eigenvalue is:')
print(evalues2[0]*evectors2.T[0])
print(np.dot(np.dot(A,A.T),evectors2.T[0]))


[[8 1 4 4]
 [1 7 9 9]
 [3 1 2 9]
 [9 1 3 1]]
[[ 97  87  69  89]
 [ 87 212 109  52]
 [ 69 109  95  43]
 [ 89  52  43  92]]
The eigenvalues are:
[16.54181955+0.j          5.39713395+0.j         -1.96947675+1.50308452j
 -1.96947675-1.50308452j]
The eigenvectors are:
[[ 0.43046466+0.j          0.13121142+0.j          0.15620955+0.07043601j
   0.15620955-0.07043601j]
 [ 0.73810537+0.j         -0.98468254+0.j          0.47713067+0.25275973j
   0.47713067-0.25275973j]
 [ 0.3670873 +0.j          0.06905261+0.j         -0.76930008+0.j
  -0.76930008-0.j        ]
 [ 0.36762421+0.j          0.09173659+0.j          0.23421772-0.18004342j
   0.23421772+0.18004342j]]
The Inner product of eigenvectors are:
[[ 1.        +0.j         -0.61124466+0.j          0.22311922+0.1506952j
   0.22311922-0.1506952j ]
 [-0.61124466+0.j          1.        +0.j         -0.48096161-0.25616265j
  -0.48096161+0.25616265j]
 [ 0.22311922+0.1506952j  -0.48096161-0.25616265j  0.79747131+0.17886568j
   1.        +0.j        

In [15]:
np.linalg.multi_dot([evectors1.T,A,evectors1])

array([[3.81966011e-01, 0.00000000e+00],
       [1.66533454e-16, 2.61803399e+00]])

In [6]:
A = np.array([[1,0.4,0.2],[0.4,1,-0.1],[0.2,-0.1,1]])
evalues1, evectors1 = np.linalg.eig(A)
print(evectors1)
print(evalues1)

[[-0.67028426  0.72847433  0.14157742]
 [ 0.62554549  0.65727018 -0.42034361]
 [ 0.39926415  0.19318659  0.89625169]]
[0.5075656 1.413941  1.0784934]


In [1]:
a = np.random.rand(3,3)  # generate a random array shaped (3,3)

a = (a + a.T)/2  # a becomes a random simmetric matrix    

evalues1, evectors1 = np.linalg.eig(a)

In [3]:
evectors1

array([[-0.71002836, -0.52434846,  0.4700196 ],
       [-0.51145899, -0.07477653, -0.856048  ],
       [-0.48401388,  0.8482141 ,  0.21508928]])

In [6]:
np.dot(evectors1[1],evectors1[2])

1.6651603187104127e-16

In [2]:
evalues1

array([ 1.75529111,  0.08388121, -0.53694962])

## Singular value decomposition
Despite most matrices are non-sqare and not symmetric, we could create symmetric (square) matrix for every matrix $\mathbf{A}$.

For example: $\mathbf{A}\mathbf{A}^{\top}$, $\mathbf{A}^{\top}\mathbf{A}$ are symmetric matrix.

It is easy to see $\mathbf{A}\mathbf{A}^{\top}$, $\mathbf{A}^{\top}\mathbf{A}$ are both semi-definite (a matrix $\mathbf{M}$ is semi-definate means $\forall \mathbf{v},\langle \mathbf{v},\mathbf{M}\mathbf{v}\rangle \geq 0$).

Therefore we could write down the following two equations.

$$\mathbf{A}\mathbf{A}^{\top} = \mathbf{U}\Lambda_1^2\mathbf{U}^{\top}$$
$$\mathbf{A}^{\top}\mathbf{A} = \mathbf{V}\Lambda_2^2\mathbf{V}^{\top}$$

The proof of singular value decomposition would show that essentially $\Lambda_1^2 =\Lambda_2^2$, therefore it is easy to guess 
$$\mathbf{A} = \mathbf{U}\Lambda\mathbf{V}^{\top}$$
which is the singular value decomposition we want.

Singular value decomposition is actually a direct result of spectral theory (spectral decomposition). 
Assuming spectral theory holds, we have a full set of eigenvalues and eigenvectors for $\mathbf{A}^{\top}\mathbf{A}$ as  $\{\lambda_i\}$ and $\{\mathbf{v}_i\}$

The proof of singular value decomposition is a one liner. 

$\langle \mathbf{v}_i,\mathbf{A}^{\top}\mathbf{A}\mathbf{v}_j\rangle = \langle \mathbf{v}_i,\lambda_j\mathbf{v}_j\rangle=0$, since $\mathbf{v}_i \perp \mathbf{v}_j$ for $i\neq j$.
On the other hand, $\langle \mathbf{v}_i,\mathbf{A}^{\top}\mathbf{A}\mathbf{v}_j\rangle = \langle \mathbf{A}\mathbf{v}_i,\mathbf{A}\mathbf{v}_j\rangle$. $\sigma_i\mathbf{u}_i \triangleq\mathbf{A}\mathbf{v}_i$, then we have $\mathbf{U}\Sigma= \mathbf{A}\mathbf{V} $ and $\mathbf{A} = \mathbf{U}\Sigma\mathbf{V}^{\top} $.


### Singular value decomposition for some common matrices

Scalar

reflection

rotation

projection matrix

jordan form failed matrix

In [3]:
A = np.array([[1,0],[0,-1]])
U,sigma,VT = np.linalg.svd(A)
print(U)
print(sigma)
print(VT)
print(np.linalg.multi_dot([U,np.diag(sigma),VT]))

[[1. 0.]
 [0. 1.]]
[1. 1.]
[[ 1.  0.]
 [-0. -1.]]
[[ 1.  0.]
 [ 0. -1.]]


In [29]:
A = np.array([[1,0],[0,5]])
U,sigma,VT = np.linalg.svd(A)
print(U)
print(sigma)
print(VT)
print(np.linalg.multi_dot([U,np.diag(sigma),VT]))

[[0. 1.]
 [1. 0.]]
[5. 1.]
[[0. 1.]
 [1. 0.]]
[[1. 0.]
 [0. 5.]]


In [32]:
A = np.array([[ 0.70710678, -0.70710678],
 [ 0.70710678,  0.70710678]])
U,sigma,VT = np.linalg.svd(A)
print(U)
print(sigma)
print(VT)
print(np.linalg.multi_dot([U,np.diag(sigma),VT]))

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[1. 1.]
[[-1. -0.]
 [ 0.  1.]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [16]:
import sympy as sp
alpha, beta,theta, x1,y1,lambda1 = sp.symbols('alpha, beta,theta, x1,y1,lambda1',real=True)

B = sp.Matrix([[sp.cos(alpha),-sp.sin(alpha),0],[sp.sin(alpha),sp.cos(alpha),0],[0,0,1]])
C = sp.Matrix([[1,0,0],[0,sp.cos(theta),-sp.sin(theta)],[0,sp.sin(theta),sp.cos(theta)]])

In [17]:
B

Matrix([
[cos(alpha), -sin(alpha), 0],
[sin(alpha),  cos(alpha), 0],
[         0,           0, 1]])

In [18]:
C

Matrix([
[1,          0,           0],
[0, cos(theta), -sin(theta)],
[0, sin(theta),  cos(theta)]])

In [25]:
A = (B*C).subs([(alpha, sp.pi / 4),(theta, sp.pi / 4)])
A

Matrix([
[sqrt(2)/2,      -1/2,       1/2],
[sqrt(2)/2,       1/2,      -1/2],
[        0, sqrt(2)/2, sqrt(2)/2]])

In [30]:
np.array(A).astype(np.float64)

array([[ 0.70710678, -0.5       ,  0.5       ],
       [ 0.70710678,  0.5       , -0.5       ],
       [ 0.        ,  0.70710678,  0.70710678]])

In [29]:
U,sigma,VT = np.linalg.svd(np.array(A).astype(np.float64))
print(U)
print(sigma)
print(VT)
print(np.linalg.multi_dot([U,np.diag(sigma),VT]))

[[-0.70710678  0.5         0.5       ]
 [-0.70710678 -0.5        -0.5       ]
 [ 0.          0.70710678 -0.70710678]]
[1. 1. 1.]
[[-1. -0. -0.]
 [ 0.  0.  1.]
 [-0. -1. -0.]]
[[ 0.70710678 -0.5         0.5       ]
 [ 0.70710678  0.5        -0.5       ]
 [ 0.          0.70710678  0.70710678]]


In [3]:
A = np.array([[0,0,0,0],[1,0,0,0],[0,1,0,0],[0,0,1,0]])
U,sigma,VT = np.linalg.svd(A)
print(U)
print(sigma)
print(VT)
print(np.linalg.multi_dot([U,np.diag(sigma),VT]))

[[ 0.  0.  0. -1.]
 [ 0.  0. -1.  0.]
 [-1.  0.  0.  0.]
 [ 0. -1.  0.  0.]]
[1. 1. 1. 0.]
[[-0. -1. -0. -0.]
 [-0. -0. -1. -0.]
 [-1. -0. -0. -0.]
 [ 0.  0.  0.  1.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
